/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paginas;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Marcielli
 */
public class Google extends javax.swing.JInternalFrame {

    /**
     * Creates new form Google
     */
    public Google() {
        initComponents();
        
        this.removeTitleBar();
        
    }

     //   Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void removeTitleBar(){
        putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPaneBGGoogle = new javax.swing.JDesktopPane();
        jPanelBGGoogle = new javax.swing.JPanel();
        jLabelLogoGoogle = new javax.swing.JLabel();
        jPanelBgPesquisaGoogle = new javax.swing.JPanel();
        jTextFieldPesquisaGoogle = new javax.swing.JTextField();
        jButtonPesquisaVoz = new javax.swing.JButton();
        jPanelLadoEsquerdoPesquisa = new javax.swing.JPanel();
        jPanelLadoDireitoPesquisa = new javax.swing.JPanel();
        jPanelBGIconesAcimaNaDireita = new javax.swing.JPanel();
        jLabelPerfilGooglePlus = new javax.swing.JLabel();
        jButtonNotificacaoDireitaSuperior = new javax.swing.JButton();
        jButtonGoogleAppsDireitaSuperior = new javax.swing.JButton();
        jButtonImagensDireitaSuperior = new javax.swing.JButton();
        jButtonGmailDireitaSuperior = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBGGoogle.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLogoGoogle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelLogoGoogle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/google-logo.png"))); // NOI18N

        jPanelBgPesquisaGoogle.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBgPesquisaGoogle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanelBgPesquisaGoogle.setMaximumSize(new java.awt.Dimension(100, 100));
        jPanelBgPesquisaGoogle.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelBgPesquisaGoogleAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTextFieldPesquisaGoogle.setBorder(null);
        jTextFieldPesquisaGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaGoogleActionPerformed(evt);
            }
        });

        jButtonPesquisaVoz.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPesquisaVoz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/pesquisa-voz.png"))); // NOI18N
        jButtonPesquisaVoz.setBorder(null);
        jButtonPesquisaVoz.setBorderPainted(false);
        jButtonPesquisaVoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaVozActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBgPesquisaGoogleLayout = new javax.swing.GroupLayout(jPanelBgPesquisaGoogle);
        jPanelBgPesquisaGoogle.setLayout(jPanelBgPesquisaGoogleLayout);
        jPanelBgPesquisaGoogleLayout.setHorizontalGroup(
            jPanelBgPesquisaGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBgPesquisaGoogleLayout.createSequentialGroup()
                .addComponent(jTextFieldPesquisaGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPesquisaVoz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBgPesquisaGoogleLayout.setVerticalGroup(
            jPanelBgPesquisaGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBgPesquisaGoogleLayout.createSequentialGroup()
                .addComponent(jTextFieldPesquisaGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButtonPesquisaVoz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelLadoEsquerdoPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelLadoEsquerdoPesquisaLayout = new javax.swing.GroupLayout(jPanelLadoEsquerdoPesquisa);
        jPanelLadoEsquerdoPesquisa.setLayout(jPanelLadoEsquerdoPesquisaLayout);
        jPanelLadoEsquerdoPesquisaLayout.setHorizontalGroup(
            jPanelLadoEsquerdoPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanelLadoEsquerdoPesquisaLayout.setVerticalGroup(
            jPanelLadoEsquerdoPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelLadoDireitoPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelLadoDireitoPesquisaLayout = new javax.swing.GroupLayout(jPanelLadoDireitoPesquisa);
        jPanelLadoDireitoPesquisa.setLayout(jPanelLadoDireitoPesquisaLayout);
        jPanelLadoDireitoPesquisaLayout.setHorizontalGroup(
            jPanelLadoDireitoPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        jPanelLadoDireitoPesquisaLayout.setVerticalGroup(
            jPanelLadoDireitoPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanelBGIconesAcimaNaDireita.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPerfilGooglePlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerfilGooglePlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/perfil-google-plus.png"))); // NOI18N

        jButtonNotificacaoDireitaSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNotificacaoDireitaSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/notificacao-google.png"))); // NOI18N
        jButtonNotificacaoDireitaSuperior.setBorder(null);
        jButtonNotificacaoDireitaSuperior.setBorderPainted(false);
        jButtonNotificacaoDireitaSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotificacaoDireitaSuperiorActionPerformed(evt);
            }
        });

        jButtonGoogleAppsDireitaSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGoogleAppsDireitaSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/google-apps.png"))); // NOI18N
        jButtonGoogleAppsDireitaSuperior.setBorder(null);
        jButtonGoogleAppsDireitaSuperior.setBorderPainted(false);
        jButtonGoogleAppsDireitaSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGoogleAppsDireitaSuperiorMouseClicked(evt);
            }
        });
        jButtonGoogleAppsDireitaSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoogleAppsDireitaSuperiorActionPerformed(evt);
            }
        });

        jButtonImagensDireitaSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonImagensDireitaSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/btn-imagens.png"))); // NOI18N
        jButtonImagensDireitaSuperior.setBorder(null);
        jButtonImagensDireitaSuperior.setBorderPainted(false);
        jButtonImagensDireitaSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagensDireitaSuperiorActionPerformed(evt);
            }
        });

        jButtonGmailDireitaSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGmailDireitaSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/btn-gmail.png"))); // NOI18N
        jButtonGmailDireitaSuperior.setBorder(null);
        jButtonGmailDireitaSuperior.setBorderPainted(false);
        jButtonGmailDireitaSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGmailDireitaSuperiorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBGIconesAcimaNaDireitaLayout = new javax.swing.GroupLayout(jPanelBGIconesAcimaNaDireita);
        jPanelBGIconesAcimaNaDireita.setLayout(jPanelBGIconesAcimaNaDireitaLayout);
        jPanelBGIconesAcimaNaDireitaLayout.setHorizontalGroup(
            jPanelBGIconesAcimaNaDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGIconesAcimaNaDireitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGmailDireitaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImagensDireitaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGoogleAppsDireitaSuperior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNotificacaoDireitaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPerfilGooglePlus)
                .addContainerGap())
        );
        jPanelBGIconesAcimaNaDireitaLayout.setVerticalGroup(
            jPanelBGIconesAcimaNaDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPerfilGooglePlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBGIconesAcimaNaDireitaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBGIconesAcimaNaDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGoogleAppsDireitaSuperior)
                    .addComponent(jButtonNotificacaoDireitaSuperior)
                    .addGroup(jPanelBGIconesAcimaNaDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonGmailDireitaSuperior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonImagensDireitaSuperior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBGGoogleLayout = new javax.swing.GroupLayout(jPanelBGGoogle);
        jPanelBGGoogle.setLayout(jPanelBGGoogleLayout);
        jPanelBGGoogleLayout.setHorizontalGroup(
            jPanelBGGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGGoogleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGGoogleLayout.createSequentialGroup()
                .addGroup(jPanelBGGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBGGoogleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelBGIconesAcimaNaDireita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBGGoogleLayout.createSequentialGroup()
                        .addComponent(jPanelLadoEsquerdoPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBgPesquisaGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelLadoDireitoPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBGGoogleLayout.setVerticalGroup(
            jPanelBGGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGGoogleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBGIconesAcimaNaDireita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabelLogoGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBGGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBgPesquisaGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLadoEsquerdoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelLadoDireitoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jDesktopPaneBGGoogle.setLayer(jPanelBGGoogle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneBGGoogleLayout = new javax.swing.GroupLayout(jDesktopPaneBGGoogle);
        jDesktopPaneBGGoogle.setLayout(jDesktopPaneBGGoogleLayout);
        jDesktopPaneBGGoogleLayout.setHorizontalGroup(
            jDesktopPaneBGGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPaneBGGoogleLayout.setVerticalGroup(
            jDesktopPaneBGGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBGGoogle)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBGGoogle)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaVozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaVozActionPerformed
        jButtonPesquisaVoz.setBorderPainted(false);
    }//GEN-LAST:event_jButtonPesquisaVozActionPerformed

    private void jPanelBgPesquisaGoogleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelBgPesquisaGoogleAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelBgPesquisaGoogleAncestorAdded

    private void jButtonNotificacaoDireitaSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotificacaoDireitaSuperiorActionPerformed
        jButtonNotificacaoDireitaSuperior.setBorderPainted(false);
        //só instanciar e chamar a tela como fiz nos outros na tela Navegador.java
    }//GEN-LAST:event_jButtonNotificacaoDireitaSuperiorActionPerformed

    private void jButtonGoogleAppsDireitaSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoogleAppsDireitaSuperiorActionPerformed
        jButtonGoogleAppsDireitaSuperior.setBorderPainted(false);
    }//GEN-LAST:event_jButtonGoogleAppsDireitaSuperiorActionPerformed

    private void jButtonGoogleAppsDireitaSuperiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGoogleAppsDireitaSuperiorMouseClicked
        //só instanciar e chamar a tela como fiz nos outros na tela Navegador.java
    }//GEN-LAST:event_jButtonGoogleAppsDireitaSuperiorMouseClicked

    private void jButtonImagensDireitaSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagensDireitaSuperiorActionPerformed
        jButtonImagensDireitaSuperior.setBorderPainted(false);       
    }//GEN-LAST:event_jButtonImagensDireitaSuperiorActionPerformed

    private void jButtonGmailDireitaSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGmailDireitaSuperiorActionPerformed
        jButtonGmailDireitaSuperior.setBorderPainted(false);
    }//GEN-LAST:event_jButtonGmailDireitaSuperiorActionPerformed

    private void jTextFieldPesquisaGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaGoogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaGoogleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGmailDireitaSuperior;
    private javax.swing.JButton jButtonGoogleAppsDireitaSuperior;
    private javax.swing.JButton jButtonImagensDireitaSuperior;
    private javax.swing.JButton jButtonNotificacaoDireitaSuperior;
    private javax.swing.JButton jButtonPesquisaVoz;
    private javax.swing.JDesktopPane jDesktopPaneBGGoogle;
    private javax.swing.JLabel jLabelLogoGoogle;
    private javax.swing.JLabel jLabelPerfilGooglePlus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBGGoogle;
    private javax.swing.JPanel jPanelBGIconesAcimaNaDireita;
    private javax.swing.JPanel jPanelBgPesquisaGoogle;
    private javax.swing.JPanel jPanelLadoDireitoPesquisa;
    private javax.swing.JPanel jPanelLadoEsquerdoPesquisa;
    private javax.swing.JTextField jTextFieldPesquisaGoogle;
    // End of variables declaration//GEN-END:variables
}
