/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package navegador;

import configuracao.ConfiguracaoPrincipal;
import paginas.TecGirl;
import paginas.FatecCruzeiro;
import paginas.Facebook;
import paginas.Google;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTabbedPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Marcielli
 */
public class JInternalBase extends javax.swing.JInternalFrame {

    public String pesquisa;
 
    /**
     * Creates new form NovoJInternalBase
     */
    public JInternalBase() throws PropertyVetoException {
        initComponents();
        
        this.removeTitleBar();
//        
//        Google google = new Google();
//        jDesktopPaneBG.add(google);
//        google.setMaximum(true);
//        google.setVisible(true);
//        google.setPosicao();


    }

         //   Abrir jInternalFrame Centralizado
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void removeTitleBar(){
        putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBGAcimaDasAbas = new javax.swing.JPanel();
        jDesktopPaneBG = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonAvancar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jButtonConfiguracao = new javax.swing.JButton();
        jPanelBG = new javax.swing.JPanel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelIconPesquisa = new javax.swing.JLabel();
        jLabelIconEstrela = new javax.swing.JLabel();
        jButtonEnter = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanelBGAcimaDasAbas.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jDesktopPaneBG.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneBGLayout = new javax.swing.GroupLayout(jDesktopPaneBG);
        jDesktopPaneBG.setLayout(jDesktopPaneBGLayout);
        jDesktopPaneBGLayout.setHorizontalGroup(
            jDesktopPaneBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPaneBGLayout.setVerticalGroup(
            jDesktopPaneBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/btn-setaVoltar.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setBorderPainted(false);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonAvancar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/btn-setaSeguir.png"))); // NOI18N
        jButtonAvancar.setBorder(null);
        jButtonAvancar.setBorderPainted(false);
        jButtonAvancar.setContentAreaFilled(false);

        jButtonAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/btn-setaRefresh.png"))); // NOI18N
        jButtonAtualizar.setBorder(null);
        jButtonAtualizar.setBorderPainted(false);
        jButtonAtualizar.setContentAreaFilled(false);

        jButtonInicio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Google/btn-setaHome.png"))); // NOI18N
        jButtonInicio.setBorder(null);
        jButtonInicio.setBorderPainted(false);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jButtonConfiguracao.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConfiguracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConfiguracao.setText("...");
        jButtonConfiguracao.setBorder(null);
        jButtonConfiguracao.setBorderPainted(false);
        jButtonConfiguracao.setContentAreaFilled(false);
        jButtonConfiguracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfiguracaoMouseClicked(evt);
            }
        });
        jButtonConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracaoActionPerformed(evt);
            }
        });

        jPanelBG.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jTextFieldPesquisa.setText("tecgirl.com.br");
        jTextFieldPesquisa.setBorder(null);
        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jLabelIconPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BarraPesquisa/pesquisa.png"))); // NOI18N

        jLabelIconEstrela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BarraPesquisa/estrela.png"))); // NOI18N

        jButtonEnter.setBackground(new java.awt.Color(153, 204, 255));
        jButtonEnter.setBorder(null);
        jButtonEnter.setBorderPainted(false);
        jButtonEnter.setContentAreaFilled(false);
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBGLayout = new javax.swing.GroupLayout(jPanelBG);
        jPanelBG.setLayout(jPanelBGLayout);
        jPanelBGLayout.setHorizontalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGLayout.createSequentialGroup()
                .addComponent(jLabelIconPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIconEstrela))
        );
        jPanelBGLayout.setVerticalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelIconEstrela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBGAcimaDasAbasLayout = new javax.swing.GroupLayout(jPanelBGAcimaDasAbas);
        jPanelBGAcimaDasAbas.setLayout(jPanelBGAcimaDasAbasLayout);
        jPanelBGAcimaDasAbasLayout.setHorizontalGroup(
            jPanelBGAcimaDasAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBG)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBGAcimaDasAbasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jButtonConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanelBGAcimaDasAbasLayout.setVerticalGroup(
            jPanelBGAcimaDasAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGAcimaDasAbasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelBGAcimaDasAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBGAcimaDasAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelBGAcimaDasAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBGAcimaDasAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonConfiguracao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelBG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPaneBG))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGAcimaDasAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBGAcimaDasAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPaginaAtual() {
        
       pesquisa = jTextFieldPesquisa.getText();
       // System.out.println(" "+pesquisa);
        
    }
    
    public String getPaginaAtual(String pes) {
    
        pes = pesquisa;
        
        return pes;
        
    }
    
    
    public void fecharFacebook() {
     
        Facebook facebook = new Facebook();
        
        facebook.dispose();
        
    }
    
    
    
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed

    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
     
    
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracaoActionPerformed
              
        ConfiguracaoPrincipal config1 = new ConfiguracaoPrincipal();
        
        try {        
        jDesktopPaneBG.add(config1);
        config1.setVisible(true);
        config1.setPosicao();
        config1.setMaximum(true);
        
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JInternalBase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonConfiguracaoActionPerformed

    private void jButtonConfiguracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfiguracaoMouseClicked
       
    }//GEN-LAST:event_jButtonConfiguracaoMouseClicked

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        jButtonEnterActionPerformed(evt);
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
      //tentar deixar fazer login com o ping tb
        
        if((jTextFieldPesquisa.getText().equals("www.facebook.com.br")) || (jTextFieldPesquisa.getText().equals("facebook.com.br")) || (jTextFieldPesquisa.getText().equals("31.13.85.36"))) {

            
        JTabbedPane tabbedPane = new JTabbedPane();       
        System.out.println("Facebook: "+tabbedPane.getSelectedIndex());
   
            
            Facebook obj1=new Facebook();
            jDesktopPaneBG.add(obj1);
            try{
                obj1.setMaximum(true);
                obj1.setVisible(true);
                obj1.setPosicao();
                
            } catch (PropertyVetoException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        } else if ((jTextFieldPesquisa.getText().equals("www.google.com.br")) || (jTextFieldPesquisa.getText().equals("google.com.br")) || (jTextFieldPesquisa.getText().equals("172.217.29.67"))) { //fazer || .com
            
        JTabbedPane tabbedPane = new JTabbedPane();       
        System.out.println("Google: "+tabbedPane.getSelectedIndex());
        
            Google obj2=new Google();
            jDesktopPaneBG.add(obj2);
            try{
                obj2.setMaximum(true);
                obj2.setVisible(true);
                obj2.setPosicao();

                
                
            } catch (PropertyVetoException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        } else if (jTextFieldPesquisa.getText().equals("www.tecgirl.com.br") || jTextFieldPesquisa.getText().equals("tecgirl.com.br")) {
            
        JTabbedPane tabbedPane = new JTabbedPane();       
        System.out.println("TecGirl: "+tabbedPane.getSelectedIndex());
        
            TecGirl obj3=new TecGirl();
            jDesktopPaneBG.add(obj3);
            try{
                obj3.setMaximum(true);
                obj3.setVisible(true);
                obj3.setPosicao();
                
                

            } catch (PropertyVetoException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        } else if (jTextFieldPesquisa.getText().equals("www.fateccruzeiro.edu.br") || jTextFieldPesquisa.getText().equals("fateccruzeiro.edu.br")) {
                        
        JTabbedPane tabbedPane = new JTabbedPane();       
        System.out.println("FatecCruzeiro: "+tabbedPane.getSelectedIndex());
        
            FatecCruzeiro obj4=new FatecCruzeiro();
            jDesktopPaneBG.add(obj4);
            try{
                obj4.setMaximum(true);
                obj4.setVisible(true);
                obj4.setPosicao();

            } catch (PropertyVetoException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        }

        //
        //        else {
            //
            //            JOptionPane.showMessageDialog(rootPane, "Você errou o site. Digite www.facebook.com.br na barra de pesquisa");
            //
            //        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonAvancar;
    private javax.swing.JButton jButtonConfiguracao;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JDesktopPane jDesktopPaneBG;
    private javax.swing.JLabel jLabelIconEstrela;
    private javax.swing.JLabel jLabelIconPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JPanel jPanelBGAcimaDasAbas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
